name: 02 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    # Permisos necesarios para el trabajo
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          cd inclusionlectora_api
          npm install
          cd ..
          cd inclusionlectora_web
          npm install
      
      # Construir y probar el proyecto
      - name: Test project
        run: |
          cd inclusionlectora_web
          npm test
          cd ..
          cd inclusionlectora_api
          npm test
