name: 02 Build pipeline

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22 for inclusionlectora_api
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: inclusionlectora_api/package-lock.json

      - name: Install dependencies for inclusionlectora_api
        run: |
          cd inclusionlectora_api
          npm install

      - name: Set up Node.js 22 for inclusionlectora_web
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: inclusionlectora_web/package-lock.json

      - name: Install dependencies for inclusionlectora_web
        run: |
          cd inclusionlectora_web
          npm install

      - name: Test inclusionlectora_web
        run: |
          cd inclusionlectora_web
          npm test

      - name: Test inclusionlectora_api
        run: |
          cd inclusionlectora_api
          npm test
          
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: test-results