name: 06 Build Docker Image

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      image-tag:
        description: "The tag of my image test"
        value: ${{ jobs.docker.outputs.image-tag }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.1.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=pr
          type=ref,event=tag
          type=ref,event=branch
          type=schedule,pattern=main
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./dockerfile  # Asegúrate de que el Dockerfile esté en la raíz o ajusta el path si está en otra ubicación
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
