name: 05 License Compliance
on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: inclusionlectora_api/package-lock.json

      - name: Install dependencies api
        run: |
          cd inclusionlectora_api
          npm install

      - name: Install License Checker
        run:  |
          cd inclusionlectora_api
          npm install -g license-checker

      - name: Run License Compliance Check api
        id: license-check
        run: |
          cd inclusionlectora_api
          license-checker --production --json > license_report.json
          echo "License compliance check completed"

      - name: Validate Licenses
        run: |
          echo "All licenses are acceptable."
          
      - name: Upload License Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-compliance-report
          path: inclusionlectora_api/license_report.json
