name: 01 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:


# Otorgamos los permisos globalmente
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write


jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit  

  sca:
    needs: build
    name: SCA
    uses: ./.github/workflows/sca.yml
    secrets: inherit

  license-compliance:
    needs: build
    name: License Compliance
    uses: ./.github/workflows/license-compliance.yml
    secrets: inherit

